name: Create Pull Request on Main Update

on:
  push:
    branches:
      - main
      - actions

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: create pull request
      run: gh pr create -B deploy -H main --title 'Merge main into deploy' --body 'Created by Github action'
      env:
          GH_TOKEN: ${{ github.token }}

  
